server:
  port: 9001

spring:
  application:
    name: nacos-provide
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        server-addr: localhost:345
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/payment?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springcloud.entities
