server:
  port: 9002

spring:
  application:
    name: nacos-provide
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848
        server-addr: localhost:345
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/payment?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  mapper-locations: classpath:maaper/*.xml
  type-aliases-package: com.springcloud.entities