server:
  port: 90

spring:
  application:
    name: nacos-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率值介于0到1之间，1表示全部采集
      probability: 1

#消费者将要去访问的微服务名称（非固定，为提供者的名称）
service-url:
  nacos-user-service: http://nacos-provide