server:
  port: 80

spring:
  application:
    name: cloud-order-feign-service
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#ribbon:
#读取资源时间
#  ReadTimeout:
#连接时间
#  ConectTimeout:
logging:
  level:
#    feign日志以什么级别监控哪个接口
    com.springcloud.service.PaymentFeignService: debug
